version: "3.9"
services:
  video_processing:
    build:
      dockerfile: Dockerfile
      context: ./video_processing
    ports:
      - "10801:10801"
    volumes:
      - ./video_endpoints/videos/processed:/video_processing/videos/processed
      - ./video_endpoints/videos/uploaded:/video_processing/videos/uploaded
  video_endpoints:
    build:
      dockerfile: Dockerfile
      context: ./video_endpoints
    ports:
      - "80:80"
      - "5001:5001"
      - "10444:10444"
    environment:
      - WEBAPP=https://navigait-web-app.herokuapp.com
      - WEBSOC=ws://video_processing:10801/
    volumes:
      - ./video_endpoints/videos/processed:/video_endpoints/videos/processed
      - ./video_endpoints/videos/uploaded:/video_endpoints/videos/uploaded
      - ./video_endpoints/letsencrypt:/etc/letsencrypt
    depends_on:
      - video_processing