version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "80:80"
      - "5001:5001"
      - "10444:10444"
    environment:
      - WEBAPP="https://navigait-web-app.herokuapp.com"
    volumes:
      - ./app/videos/processed:/app/videos/processed
      - ./app/videos/uploaded:/app/videos/uploaded
      - ./app/letsencrypt:/etc/letsencrypt