version: "3.9"
services:
  upload_endpoint:
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "5001:5001"
    environment:
      - WEBAPP="https://navigait-web-app.herokuapp.com"
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      - app