version: "3.9"
services:
  video_processing:
    build:
      dockerfile: Dockerfile
      context: ./video_processing
    ports:
      - "10801:10801"
    volumes:
      - ./app/videos/processed:/video_processing/videos/processed
      - ./app/videos/uploaded:/video_processing/videos/uploaded
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "80:80"
      - "5001:5001"
      - "10444:10444"
    environment:
      - WEBAPP=https://navigait-web-app.herokuapp.com
      - WEBSOC=ws://video_processing:10801/
    volumes:
      - ./app/videos/processed:/app/videos/processed
      - ./app/videos/uploaded:/app/videos/uploaded
      - ./app/letsencrypt:/etc/letsencrypt
    depends_on:
      - video_processing